openapi: 3.0.0
info:
  title: RW-Budget API
  version: 1.0.0
  description: API to access data that powers RW-Budget.
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.example.com/{version}
    variables:
      version:
        default: v1
    description: Production server
  - url: https://staging-api.example.com/{version}
    variables:
      version:
        default: v1
    description: Staging server
  - url: http://localhost:8080/{version}
    variables:
      version:
        default: v1
    description: Local development server

paths:
  /health:
    get:
      summary: Health check
      description: Returns the health status of the API
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2023-01-01T12:00:00Z"

  /accounts:
    get:
      summary: List all accounts
      description: Returns a list of accounts
      operationId: ReadAccounts
      tags:
        - Accounts
      parameters:
        - name: name
          in: query
          description: Filter accounts by account name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  accounts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Account'

    post:
      summary: Create a new account
      description: Creates a new account
      operationId: createaccount
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/account_input'
      responses:
        '201':
          description: account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Invalid input
  /accounts/{id}:
    get:
      summary: Get account by ID
      description: Returns a single account
      operationId: getaccount
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: account ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: account found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: account not found

    put:
      summary: Update account
      description: Updates an existing account
      operationId: PutAccount
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: account ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/account_input'
      responses:
        '200':
          description: account updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: account not found

    delete:
      summary: Delete account
      description: Deletes an account
      operationId: DeleteAccount
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: Account ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Account deleted successfully
        '404':
          description: Account not found

  /cashflows/summary/{year}/{month}:
    get:
      summary: Get cashflow summary for the provided year and month.
      tags:
        - Cashflows
      parameters:
        - name: year
          in: path
          description: The year for which to return a cashflow summary.
          required: true
          schema:
            type: string
        - name: month
          in: path
          description: The year for which to return a cashflow summary in combination with the year parameter.
          required: true
          schema:
            type: string

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/cashflow_summary'
        '404':
          description: Data not found for the year and month provided.
        '500':
          description: Internal server error.

  /cashflows/chart/{year}/{month}:
    get:
      summary: Retrieve cashflow data for the year and month provided formatted for a cashflow chart.
      tags:
        - Cashflows
      parameters:
        - name: year
          in: path
          description: The year for which to return a cashflow summary.
          required: true
          schema:
            type: string
        - name: month
          in: path
          description: The year for which to return a cashflow summary in combination with the year parameter.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/cashflow_chart'
        '404':
          description: Data not found for the year and month provided.
        '500':
          description: Internal server error.
  /cashflows/card_balances/{year}/{month}:
    get:
      summary: Retrieve card balance data for the year and month provided.
      tags:
        - Cashflows
      parameters:
        - name: year
          in: path
          description: The year for which to return a cashflow summary.
          required: true
          schema:
            type: string
        - name: month
          in: path
          description: The year for which to return a cashflow summary in combination with the year parameter.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/cashflow_card_balances'
        '404':
          description: Data not found for the year and month provided.
        '500':
          description: Internal server error.

  /categories:
    get:
      summary: Retrieve categories
      parameters:
        - name: name
          in: query
          description: Filter accounts by account name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Unable to locate categories
        '500':
          description: Internal server error
    post:
      summary: Create a new category
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/category_input'
      responses:
        '200':
          description: OK

  /categories/:id:
    get:
      summary: Create a new category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          description: account ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    put:
      summary: Create a new category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          description: account ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    delete:
      summary: Create a new category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          description: account ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK

components:
  schemas:
    Account:
      type: object
      required:
        - id
        - name
      properties:
        accountid:
          type: string
          format: int
          example: "1"
        account_name:
          type: string
          example: "My Bank Account"
        account_type:
          type: string
          example: "Checking"
        rewards_features:
          type: string
          example: "2x at Restaurants"
        payment_day:
          type: string
          example: "3rd"
        statement_day:
          type: string
          example: "5th"
    account_input:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
          example: "My Bank Account"
        type:
          type: string
          example: "Checking"
        features:
          type: string
          example: "2x points at restaurants"
        payment_day:
          type: string
          description: The day payment is due
          example: "3rd"
        statement_day:
          type: string
          description: The day statements are generated
          example: "5th"
    cashflow_summary:
      type: object
      properties:
        flow_year:
          type: integer
          example: 2026
        flow_month:
          type: integer
          example: 01
        cashflow_group:
          type: string
          description: |
            The cashflow category of the amount.
            expens: Cash out due to expenses.
            income: Cash in due to income.
            remain: Cash remaining from income less expenses.
          enum: [expens, income, remain]
          example: remain
        month_group:
          type: string
          description: |
            The paycheck or part of the month of the amount.
            top: The first half of the month or the first paycheck
            bot: The second half of the month or the second paycheck 
            sum: The combination of both halves paychecks for the month
          enum: [top, bot, sum]
          example: sum
        amount:
          type: number
          format: float
          example: 123.45
    cashflow_chart:
      type: object
      properties:
        tran_month_name:
          type: string
          description: The full name of the month for display on a chart axis
          example: January
        cashflow_category:
          # ToDo: Align this with CashflowSummary month group
          type: string
          description: |
            The paycheck or part of the month of the amount.
            top: The first half of the month or the first paycheck
            bot: The second half of the month or the second paycheck 
            total: The combination of both halves or paychecks for the month
          enum: [top, bot, total]
          example: total
        amount:
          type: number
          format: float
          example: 123.45
    cashflow_card_balances:
      type: object
      properties:
        flow_year:
          type: integer
          example: 2026
        flow_month:
          type: integer
          example: 01
        accountid:
          type: integer
          example: 1
        account_name:
          type: string
          example: Credit Card 1
        chg_bal:
          description: The sum of charges to the card for the month through the current date.
          type: number
          format: float
          example: 123.45
        pmt_bal:
          description: The sum of payments applied to the card for the month through the curent date.
          type: number
          format: float
          example: 123.45
        cur_bal:
          description: The current balance of the card for the month through the current date (chg_bal - pmt_bal)
          type: number
          format: float
          example: 123.45
        pnd_bal:
          description: |
            The sum of charges to the card less payments applied to the card for the whole month.
            This includes expected or pending charges or payments that are not yet posted.
          type: number
          format: float
          example: 123.45
    category:
      type: object
    category_input:
      type: object

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - BearerAuth: []
  - ApiKeyAuth: []

tags:
  - name: Health
    description: Health check endpoints
  - name: Accounts
    description: Account management endpoints