openapi: 3.0.0
info:
  title: RW-Budget API
  version: 1.0.0
  description: API to access data that powers RW-Budget.
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server
  - url: http://localhost:8080/
    description: Local development server

paths:
  /health:
    get:
      summary: Health check
      description: Returns the health status of the API
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2023-01-01T12:00:00Z"

  /accounts:
    get:
      summary: List all accounts
      description: Returns a list of accounts
      operationId: ReadAccounts
      tags:
        - Accounts
      parameters:
        - name: name
          in: query
          description: Filter accounts by account name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  accounts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Account'

    post:
      summary: Create a new account
      description: Creates a new account
      operationId: createaccount
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accountInput'
      responses:
        '201':
          description: account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Invalid input

  /accounts/{id}:
    get:
      summary: Get account by ID
      description: Returns a single account
      operationId: getaccount
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: account ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: account found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: account not found

    put:
      summary: Update account
      description: Updates an existing account
      operationId: PutAccount
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: account ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accountInput'
      responses:
        '200':
          description: account updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: account not found

    delete:
      summary: Delete account
      description: Deletes an account
      operationId: DeleteAccount
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: Account ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Account deleted successfully
        '404':
          description: Account not found

components:
  schemas:
    Account:
      type: object
      required:
        - id
        - name
      properties:
        accountid:
          type: string
          format: int
          example: "1"
        account_name:
          type: string
          example: "My Bank Account"
        account_type:
          type: string
          example: "Checking"
        rewards_features:
          type: string
          example: "2x at Restaurants"
        payment_day:
          type: string
          example: "3rd"
        statement_day:
          type: string
          example: "5th"

    accountInput:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
          example: "My Bank Account"
        type:
          type: string
          example: "Checking"
        features:
          type: string
          example: "2x points at restaurants"
        payment_day:
          type: string
          description: The day payment is due
          example: "3rd"
        statement_day:
          type: string
          description: The day statements are generated
          example: "5th"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - BearerAuth: []
  - ApiKeyAuth: []

tags:
  - name: Health
    description: Health check endpoints
  - name: Accounts
    description: Account management endpoints